//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestSSC.WCFBooksSorter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BooksOrder", Namespace="http://schemas.datacontract.org/2004/07/EntitySSC")]
    [System.SerializableAttribute()]
    public partial class BooksOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestSSC.WCFBooksSorter.DirectionEnum DirectionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestSSC.WCFBooksSorter.OrderEnum OrderTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestSSC.WCFBooksSorter.DirectionEnum DirectionType {
            get {
                return this.DirectionTypeField;
            }
            set {
                if ((this.DirectionTypeField.Equals(value) != true)) {
                    this.DirectionTypeField = value;
                    this.RaisePropertyChanged("DirectionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestSSC.WCFBooksSorter.OrderEnum OrderType {
            get {
                return this.OrderTypeField;
            }
            set {
                if ((this.OrderTypeField.Equals(value) != true)) {
                    this.OrderTypeField = value;
                    this.RaisePropertyChanged("OrderType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectionEnum", Namespace="http://schemas.datacontract.org/2004/07/EntitySSC.Enumerators")]
    public enum DirectionEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACENDING = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DESCENDING = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderEnum", Namespace="http://schemas.datacontract.org/2004/07/EntitySSC.Enumerators")]
    public enum OrderEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TITLE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUTHOR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EDITION = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/EntitySSC")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EditionYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EditionYear {
            get {
                return this.EditionYearField;
            }
            set {
                if ((this.EditionYearField.Equals(value) != true)) {
                    this.EditionYearField = value;
                    this.RaisePropertyChanged("EditionYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFBooksSorter.IBooksSorter")]
    public interface IBooksSorter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBooksSorter/GetBooksSorter", ReplyAction="http://tempuri.org/IBooksSorter/GetBooksSorterResponse")]
        UnitTestSSC.WCFBooksSorter.Book[] GetBooksSorter(UnitTestSSC.WCFBooksSorter.BooksOrder[] order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBooksSorter/GetBooksSorter", ReplyAction="http://tempuri.org/IBooksSorter/GetBooksSorterResponse")]
        System.Threading.Tasks.Task<UnitTestSSC.WCFBooksSorter.Book[]> GetBooksSorterAsync(UnitTestSSC.WCFBooksSorter.BooksOrder[] order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBooksSorterChannel : UnitTestSSC.WCFBooksSorter.IBooksSorter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BooksSorterClient : System.ServiceModel.ClientBase<UnitTestSSC.WCFBooksSorter.IBooksSorter>, UnitTestSSC.WCFBooksSorter.IBooksSorter {
        
        public BooksSorterClient() {
        }
        
        public BooksSorterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BooksSorterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksSorterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksSorterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnitTestSSC.WCFBooksSorter.Book[] GetBooksSorter(UnitTestSSC.WCFBooksSorter.BooksOrder[] order) {
            return base.Channel.GetBooksSorter(order);
        }
        
        public System.Threading.Tasks.Task<UnitTestSSC.WCFBooksSorter.Book[]> GetBooksSorterAsync(UnitTestSSC.WCFBooksSorter.BooksOrder[] order) {
            return base.Channel.GetBooksSorterAsync(order);
        }
    }
}
